"""Add justification ru and he

Revision ID: 1f27f7b6ad06
Revises: b83b08999ef8
Create Date: 2026-06-14 09:13:27.280667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f27f7b6ad06'
down_revision: Union[str, Sequence[str], None] = 'b83b08999ef8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_scores', sa.Column('justification_ru', sa.Text(), nullable=True))
    op.add_column('entity_scores', sa.Column('justification_he', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_scores', 'justification_he')
    op.drop_column('entity_scores', 'justification_ru')
    # ### end Alembic commands ###
