"""add_source_type_to_static_sources

Revision ID: 487bfa98c428
Revises: 1f27f7b6ad06
Create Date: 2026-06-16 15:53:39.426180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487bfa98c428'
down_revision: Union[str, Sequence[str], None] = '1f27f7b6ad06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('static_sources', sa.Column('source_type', sa.String(), nullable=False, server_default='static'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('static_sources', 'source_type')
    # ### end Alembic commands ###
