"""Add last_modified field

Revision ID: 817119a68aee
Revises: ca7d08a4ccb8
Create Date: 2026-06-11 13:32:32.561293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '817119a68aee'
down_revision: Union[str, Sequence[str], None] = 'ca7d08a4ccb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('axes', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('political_entities', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.add_column('static_sources', sa.Column('last_modified', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('static_sources', 'last_modified')
    op.drop_column('political_entities', 'last_modified')
    op.drop_column('axes', 'last_modified')
    # ### end Alembic commands ###
