"""Add letters and chairperson to party

Revision ID: b83b08999ef8
Revises: 817119a68aee
Create Date: 2026-06-11 13:38:25.258101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b83b08999ef8'
down_revision: Union[str, Sequence[str], None] = '817119a68aee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('political_entities', sa.Column('ballot_letters', sa.String(), nullable=True))
    op.add_column('political_entities', sa.Column('chairperson', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('political_entities', 'chairperson')
    op.drop_column('political_entities', 'ballot_letters')
    # ### end Alembic commands ###
