"""EntityTypes Table

Revision ID: ca7d08a4ccb8
Revises: cd067b2f606a
Create Date: 2026-06-11 10:28:58.628357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca7d08a4ccb8'
down_revision: Union[str, Sequence[str], None] = 'cd067b2f606a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_he', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('political_entities', sa.Column('entity_type_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'political_entities', 'entity_types', ['entity_type_id'], ['id'])
    op.drop_column('political_entities', 'entity_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('political_entities', sa.Column('entity_type', postgresql.ENUM('PARTY', 'LIST', 'MOVEMENT', 'POLITICIAN', name='entitytype'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'political_entities', type_='foreignkey')
    op.drop_column('political_entities', 'entity_type_id')
    op.drop_table('entity_types')
    # ### end Alembic commands ###
