"""Initial schema with political entities

Revision ID: cd067b2f606a
Revises: 
Create Date: 2026-06-11 12:54:27.462879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd067b2f606a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_he', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING_AI_PROPOSAL', 'APPROVED', 'REJECTED', 'ARCHIVED', name='approvalstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('political_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=False),
    sa.Column('name_ru', sa.String(), nullable=False),
    sa.Column('name_he', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_AI_PROPOSAL', 'APPROVED', 'REJECTED', 'ARCHIVED', name='approvalstatus'), nullable=True),
    sa.Column('entity_type', sa.Enum('PARTY', 'LIST', 'MOVEMENT', 'POLITICIAN', name='entitytype'), nullable=True),
    sa.Column('local_storage_folder', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_he'),
    sa.UniqueConstraint('name_ru')
    )
    op.create_table('static_sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('entity_scores',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('axis_id', sa.String(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('justification_en', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['axis_id'], ['axes.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['political_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questionnaire_version', sa.String(), nullable=True),
    sa.Column('axis_id', sa.String(), nullable=True),
    sa.Column('text_en', sa.String(), nullable=False),
    sa.Column('text_ru', sa.String(), nullable=False),
    sa.Column('text_he', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_AI_PROPOSAL', 'APPROVED', 'REJECTED', 'ARCHIVED', name='approvalstatus'), nullable=True),
    sa.ForeignKeyConstraint(['axis_id'], ['axes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('axis_id', sa.String(), nullable=True),
    sa.Column('static_source_id', sa.Integer(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['axis_id'], ['axes.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['political_entities.id'], ),
    sa.ForeignKeyConstraint(['static_source_id'], ['static_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_documents')
    op.drop_table('questions')
    op.drop_table('entity_scores')
    op.drop_table('static_sources')
    op.drop_table('political_entities')
    op.drop_table('axes')
    # ### end Alembic commands ###
